### PR TITLE
Se agrega nuevo query - Jhonnier

### PR DESCRIPTION
**Pull request by Hazzard1912**

### CODE REVIEW

**Review by oscar-230 — APPROVED** [review]
Good

**Review by nheredia11 — APPROVED** [review]
Good 👌

**Review by cantor11 — APPROVED** [review]
nice

**Review by XxCr1ss — APPROVED** [review]
Nice

**Review by GUERRERO13055030 — APPROVED** [review]

**Review by kevinJ1910 — APPROVED** [review]
nice

**Pull request merged**
